#!/bin/bash
# Ce script convertit tous les fichiers .eps se trouvant ../dia
# et les place dans le répertoire ../diagrams

SRC="../dia"
DEST="../schema"
VERB="-v"

if [ $(ls $SRC/ | grep .dia~ | wc -l) -gt 0 ]; then
	rm ${SRC}/*.dia~
fi

#for f in $(ls $SRC/*.dia); do
for f in $(ls $SRC/ | grep .dia); do
	tmp=$SRC/${f%.*}
	dia -n -t eps -e ${tmp}.eps $SRC/$f
	epstopdf ${tmp}.eps
	if [ $# -eq 1 ]; then
		if [ $1 = $VERB ]; then
			echo "${tmp}.eps -> ${tmp}.pdf"
		fi
	fi 
done

#for f in $(ls $SRC/*.pdf); do
for f in $(ls $SRC/ | grep .pdf); do
	mv $SRC/$f $DEST
	if [ $# -eq 1 ]; then
		if [ $1 = $VERB ]; then
			echo "mv $SRC/$f $DEST"
		fi
	fi
done

if [ $(ls $SRC/ | grep .eps | wc -l) -gt 0 ]; then
	rm ${SRC}/*.eps
fi
